// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfifqbvytedpgtgjyzqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmaWZxYnZ5dGVkcGd0Z2p5enFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NzQzMDIsImV4cCI6MjA1NzU1MDMwMn0.TlN1TG5ixaglL0R8kTFB5vJQlANeptO8lea2Zy3wGiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);